"""Increase website_link column length

Revision ID: 94486d7c6d98
Revises: 5a046455bdbf
Create Date: 2025-10-20 08:06:54.465912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94486d7c6d98'
down_revision = '5a046455bdbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.alter_column('website',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.alter_column('website',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###
